package view;


import view.MainMenu;
import model.Book;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raul
 */
public class FormMyLibrary extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormMyLibrary
     */
    public FormMyLibrary() {
        initComponents();
        this.setTitle("Minha Biblioteca");
        this.setResizable(false);
        this.setMaximizable(false);
        this.setIconifiable(false);
        this.setClosable(true);
        
        lblResultSearch.setText("");
                
        lblTitle.setText("");
        lblPublisherLabel.setVisible(false);
        lblAuthorLabel.setVisible(false);
        lblGenreLabel.setVisible(false);
        lblIsbnLabel.setVisible(false);
        
        configureTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabBooks = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblResultSearch = new javax.swing.JLabel();
        lblAuthorLabel = new javax.swing.JLabel();
        lblPublisherLabel = new javax.swing.JLabel();
        lblIsbnLabel = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblGenreLabel = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de livros ");

        tabBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabBooks);

        jLabel2.setText("Pesquisar por ISBN:");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblResultSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblResultSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResultSearch.setText("Livro encontrado!");

        lblAuthorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAuthorLabel.setText("Autor:");

        lblPublisherLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPublisherLabel.setText("Editora:");

        lblIsbnLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIsbnLabel.setText("ISBN:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("title");

        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAuthor.setText(" ");

        lblPublisher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPublisher.setText(" ");

        lblIsbn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIsbn.setText(" ");

        lblGenreLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGenreLabel.setText("Gênero:");

        lblGenre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGenre.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIsbnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGenreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultSearch)
                            .addComponent(lblTitle)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPublisherLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAuthorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 264, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblResultSearch)
                .addGap(50, 50, 50)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPublisherLabel)
                    .addComponent(lblPublisher))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthorLabel)
                    .addComponent(lblAuthor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenreLabel)
                    .addComponent(lblGenre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbnLabel)
                    .addComponent(lblIsbn))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSearch)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(161, 161, 161)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i, flag = 0;
        String isbn = txtSearch.getText();
           
        if(tabBooks.getRowCount() == 0){
            lblResultSearch.setText("Nenhum livro na biblioteca");
        }
        else{
            for(i=0; i<tabBooks.getRowCount(); i++){
                if(tabBooks.getValueAt(i, 4).toString().equals(isbn)){
                    lblResultSearch.setText("Livro encontrado!!");

                    lblPublisherLabel.setVisible(true);
                    lblAuthorLabel.setVisible(true);
                    lblGenreLabel.setVisible(true);
                    lblIsbnLabel.setVisible(true);

                    lblTitle.setText(tabBooks.getValueAt(i, 0).toString());
                    lblPublisher.setText(tabBooks.getValueAt(i, 1).toString());
                    lblAuthor.setText(tabBooks.getValueAt(i, 2).toString());
                    lblGenre.setText(tabBooks.getValueAt(i, 3).toString());
                    lblIsbn.setText(tabBooks.getValueAt(i, 4).toString());
                    
                    flag = 1;
                    break;  
                }   
            }
            if(flag != 1){
                lblPublisherLabel.setVisible(false);
                lblAuthorLabel.setVisible(false);
                lblGenreLabel.setVisible(false);
                lblIsbnLabel.setVisible(false);
                
                lblTitle.setVisible(false);
                lblPublisher.setVisible(false);
                lblAuthor.setVisible(false);
                lblGenre.setVisible(false);
                lblIsbn.setVisible(false);
                
                lblResultSearch.setText("Nenhum livro encontrado");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAuthorLabel;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblGenreLabel;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblIsbnLabel;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblPublisherLabel;
    private javax.swing.JLabel lblResultSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tabBooks;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    private void configureTable(){
        DefaultTableModel m = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m.addColumn("Título");
        m.addColumn("Editora");
        m.addColumn("Autor");
        m.addColumn("Gênero");
        m.addColumn("Isbn");
        tabBooks.setModel(m);
    }
    
}
