/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PublisherDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Publisher;

/**
 *
 * @author Raul
 */
public class FormPublisherTable extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormTableUpdate
     */
    public FormPublisherTable() {
        initComponents();
        
        this.setTitle("Tabela de editoras");
        this.setResizable(false);
        this.setMaximizable(false);
        this.setIconifiable(false);
        this.setClosable(true);

        configureTable();
        
        List<Publisher> publisherListId = new PublisherDAO().listById();
        fillTable(publisherListId);
        
        configureButtonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbId = new javax.swing.JRadioButton();
        rdbName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPublisher = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        rdbId.setText("Id");
        rdbId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIdActionPerformed(evt);
            }
        });

        rdbName.setText("Nome");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblPesquisar.setText("Pesquisar:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Editoras cadastradas");

        tabPublisher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabPublisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPublisherMouseClicked(evt);
            }
        });
        tabPublisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabPublisherKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabPublisher);

        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPesquisar)
                            .addGap(6, 6, 6)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(rdbName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdbId))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbId)
                        .addComponent(rdbName))
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbIdActionPerformed

    private void tabPublisherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPublisherMouseClicked
        //Double click
        if (evt.getClickCount() == 2) {
            //Descobrir a linha selecionada
            int linha = tabPublisher.getSelectedRow();

            //Recuperar o ID selecionado
            int id = Integer.parseInt(
                tabPublisher.getValueAt(linha, 0).toString()
            );

            //Abrir o FormCadastro
            FormRegisterPublisher f = new FormRegisterPublisher(id);
            this.getDesktopPane().add(f);
            f.setVisible(true);

            //Fechar o FormPesquisa
            //this.dispose();
        }
    }//GEN-LAST:event_tabPublisherMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        updateTablePublisher();
    }//GEN-LAST:event_formInternalFrameActivated

    private void tabPublisherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabPublisherKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtSearch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                    null, "Informe o critério de pesquisa."
                );
            } else {
                configureTable();
                // PESQUISAR POR NOME
                List<Publisher> lista = new PublisherDAO().searchByName(txtSearch.getText());
                if (lista.size() > 0) {
                    DefaultTableModel m = (DefaultTableModel) tabPublisher.getModel();
                    for (Publisher espec : lista) {
                        m.addRow(new Object[]{
                            espec.getId(),
                            espec.getName()
                        });
                    }
                    tabPublisher.setModel(m);
                } else {
                    JOptionPane.showMessageDialog(
                        null, "Nenhum registro encontrado."
                    );
                }
            }
        }
    }//GEN-LAST:event_tabPublisherKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtSearch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                    null, "Informe o critério de pesquisa."
                );
            } else {
                if(rdbName.isSelected()){
                    configureTable();
                    List<Publisher> lista = new PublisherDAO()
                        .searchByName(txtSearch.getText());
                    if (lista.size() > 0) {
                        DefaultTableModel m = (DefaultTableModel) tabPublisher.getModel();
                        for (Publisher publisher : lista) {
                            m.addRow(new Object[]{
                                publisher.getId(),
                                publisher.getName()
                            });
                        }
                            tabPublisher.setModel(m);
                    } else {
                        JOptionPane.showMessageDialog(
                            null, "Nenhum registro encontrado."
                        );
                    }   
                }
                
                else{
                    try {
                        configureTable();
                        Publisher publisher = new PublisherDAO()
                            .searchById(Integer.parseInt(txtSearch.getText()));
                        if (publisher != null) {
                            DefaultTableModel m = (DefaultTableModel) tabPublisher.getModel();

                            m.addRow(new Object[]{
                                publisher.getId(),
                                    publisher.getName()
                            });

                            tabPublisher.setModel(m);
                        } else {
                            JOptionPane.showMessageDialog(
                                null, "Nenhum registro encontrado."
                            );
                        }  
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(
                                null, "Digite apenas números."
                        );
                    } 
                }
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdbId;
    private javax.swing.JRadioButton rdbName;
    private javax.swing.JTable tabPublisher;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    private void configureButtonGroup() {

        ButtonGroup bg = new ButtonGroup();

        bg.add(rdbId);
        bg.add(rdbName);

        rdbId.setSelected(true);
    }
    
    private void fillTable(List<Publisher> publisherList) {
        
        if (publisherList.size() > 0) {
            DefaultTableModel m = (DefaultTableModel) tabPublisher.getModel();
            m.setNumRows(0);
            for (Publisher g : publisherList) {
                m.addRow(new Object[]{
                    g.getId(),
                    g.getName()
                });
            }
            tabPublisher.setModel(m);
        } else {
            JOptionPane.showMessageDialog(
                    null, "Nenhum registro encontrado."
            );
        }
    }

    private void configureTable() {
        DefaultTableModel m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        m.addColumn("Id");
        m.addColumn("Nome");

        m.setNumRows(0);
        tabPublisher.setModel(m);
    }
    
    private void updateTablePublisher(){
        List<Publisher> publisherList = null;
        
        if(rdbName.isSelected())
            publisherList = new PublisherDAO().listById();
        else 
            publisherList = new PublisherDAO().listById();
        
        fillTable(publisherList);
    }
}
