/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.BookDAO;
import controller.LoanDAO;
import controller.UserDAO;
import java.sql.Date;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Book;
import model.Loan;
import model.User;

/**
 *
 * @author 836461
 */
public class FormLoanBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormLoanLoan
     */
    public FormLoanBook() {
        initComponents();
        
        createFormatter("##/##/####").install(txtDateBorrow);
        createFormatter("##/##/####").install(txtDateReturn);
        
        DateTimeFormatter formatInput = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        LocalDate dateBorrow = LocalDate.now();
        LocalDate dateReturn;
        
        int loanTime = 5;
        switch (dateBorrow.plusDays(loanTime).getDayOfWeek()) {
            case SATURDAY:
                dateReturn = dateBorrow.plusDays(loanTime + 2);
                break;
            case SUNDAY:
                dateReturn = dateBorrow.plusDays(loanTime + 1);
                break;
            default:
                dateReturn = dateBorrow.plusDays(loanTime);
                break;
        }

        txtDateReturn.setText(dateReturn.format(formatInput));
        txtDateBorrow.setText(dateBorrow.format(formatInput));
        
        DefaultComboBoxModel n = new DefaultComboBoxModel();
        List<Book> listBook = new BookDAO().listById();
        for(Book b : listBook){
            n.addElement(b);
        }
        cbxBook.setModel(n);
        
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        List<User> listUser = new UserDAO().listById();
        for(User user : listUser){
            m.addElement(user);
        }
        cbxUser.setModel(m);      
        
        ButtonGroup bg_fg = new ButtonGroup();
        bg_fg.add(rdbReturned);
        bg_fg.add(rdbNotReturned);
        
        rdbNotReturned.setSelected(true);
    }
    
    public FormLoanBook(int id) {
        this();
        
        Loan loan = new LoanDAO().searchById(id);
        
        DateTimeFormatter formatOutput = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        LocalDate dateBorrow = LocalDate.parse(loan.getDateBorrow().toString());
        LocalDate dateReturn = LocalDate.parse(loan.getDateReturn().toString());
        
        txtDateBorrow.setText(dateBorrow.format(formatOutput));
        txtDateReturn.setText(dateReturn.format(formatOutput));

        DefaultComboBoxModel m = (DefaultComboBoxModel)cbxBook.getModel();
        
        int i;
        for (i = 0; i < m.getSize(); i++) {
            Book book = (Book)m.getElementAt(i);
            if (book.getId() == loan.getId_book()){
                break;
            }
        }
        cbxBook.setSelectedIndex(i);
        
        DefaultComboBoxModel n = (DefaultComboBoxModel)cbxUser.getModel();
         
        for (i = 0; i < n.getSize(); i++) {
            User user = (User)n.getElementAt(i);
            if (user.getId() == loan.getId_user()){
                break;
            }
        }
        cbxUser.setSelectedIndex(i);

        ButtonGroup bg_fg = new ButtonGroup();
        bg_fg.add(rdbReturned);
        bg_fg.add(rdbNotReturned);
        
        if(loan.getStatus().equals("Entregue"))
            rdbReturned.setSelected(true);
        else
            rdbNotReturned.setSelected(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPage = new javax.swing.JLabel();
        lblDataEmprestimo = new javax.swing.JLabel();
        lblDataDevolucao = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtDateBorrow = new javax.swing.JFormattedTextField();
        txtDateReturn = new javax.swing.JFormattedTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbxUser = new javax.swing.JComboBox<>();
        cbxBook = new javax.swing.JComboBox<>();
        lblLivro = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        rdbReturned = new javax.swing.JRadioButton();
        rdbNotReturned = new javax.swing.JRadioButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        lblTituloPage.setText("jLabel1");

        lblDataEmprestimo.setText("Data empréstimo: ");

        lblDataDevolucao.setText("Data devolução:");

        lblUsuario.setText("Usuário:");

        lblId.setText("Id");

        cbxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLivro.setText("Livro:");

        lblStatus.setText("Status:");

        rdbReturned.setText("Entregue");

        rdbNotReturned.setText("Não entregue");

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbReturned)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbNotReturned))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSave)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDataDevolucao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLivro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxBook, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDataEmprestimo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTituloPage)
                                        .addComponent(txtDateBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblId)
                                    .addGap(14, 14, 14))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTituloPage)
                .addGap(18, 18, 18)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataEmprestimo)
                    .addComponent(txtDateBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDevolucao)
                    .addComponent(txtDateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(cbxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLivro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(rdbReturned)
                    .addComponent(rdbNotReturned))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        //Recuperar o valor informado pelo usuário
        Loan loan = new Loan();

        DateTimeFormatter formatOutput = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        LocalDate dateBorrow = LocalDate.parse(txtDateBorrow.getText(), formatOutput);
        LocalDate dateReturn = LocalDate.parse(txtDateReturn.getText(), formatOutput);

        loan.setDateBorrow(Date.valueOf(dateBorrow.toString()));
        loan.setDateReturn(Date.valueOf(dateReturn.toString()));
        
        System.out.println(dateBorrow);
        System.out.println(dateReturn);
        
        User u = (User)cbxUser.getSelectedItem();
        loan.setId_user(u.getId());
            
        Book b = (Book)cbxBook.getSelectedItem();
        loan.setId_book(b.getId());
        
        loan.setStatus(rdbReturned.isSelected() ? rdbReturned.getName() : rdbNotReturned.getName());
    

        int res = -1;
        if (txtId.getText().isEmpty()){
            //Operação de INSERIR
            res = new LoanDAO().add(loan);
        }else{
            //Operação de ATUALIZAR
            loan.setId(Integer.parseInt(txtId.getText()));
            res = new LoanDAO().update(loan);
        }

        //Verificar se deu certo
        if (res > 0){
            txtId.setText(String.valueOf(res));
            JOptionPane.showMessageDialog(
                null,"Operação realizada com sucesso!"
            );
        }else{
            JOptionPane.showMessageDialog(
                null,"Não foi possível realizar a operação!"
            );
        }

        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxBook;
    private javax.swing.JComboBox<String> cbxUser;
    private javax.swing.JLabel lblDataDevolucao;
    private javax.swing.JLabel lblDataEmprestimo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLivro;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTituloPage;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JRadioButton rdbNotReturned;
    private javax.swing.JRadioButton rdbReturned;
    private javax.swing.JFormattedTextField txtDateBorrow;
    private javax.swing.JFormattedTextField txtDateReturn;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
    
    protected MaskFormatter createFormatter(String s) {
        MaskFormatter formatter = null;
        try {
            formatter = new MaskFormatter(s);
            formatter.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            System.err.println("formatter is bad: " + exc.getMessage());
            System.exit(-1);
        }

        return formatter;
    }
}
