package view;


import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 836461
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    //Global variables
    public MainMenu() {
        initComponents();
        this.setTitle("Sistema de Troca de livros");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workStation = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPerfil = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuItemCadastrarLivro = new javax.swing.JMenuItem();
        menuItemCadastrarGenero = new javax.swing.JMenuItem();
        menuItemCadastrarEditora = new javax.swing.JMenuItem();
        menuItemCadastrarAutor = new javax.swing.JMenuItem();
        menuVisualizar = new javax.swing.JMenu();
        menuItemVisualizarLivros = new javax.swing.JMenuItem();
        menuItemVisualizarGeneros = new javax.swing.JMenuItem();
        menuItemVisualizarAutores = new javax.swing.JMenuItem();
        menuItemVisualizarEditoras = new javax.swing.JMenuItem();
        menuItemVisualizarSobrePrograma = new javax.swing.JMenuItem();
        menuEmprestimo = new javax.swing.JMenu();
        menuItemEmprestimoEmprestar = new javax.swing.JMenuItem();
        menuItemEmprestimoVisualizar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuItemSairPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout workStationLayout = new javax.swing.GroupLayout(workStation);
        workStation.setLayout(workStationLayout);
        workStationLayout.setHorizontalGroup(
            workStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        workStationLayout.setVerticalGroup(
            workStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        menuPerfil.setText("Perfil");

        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuPerfil.add(menuItemLogout);

        jMenuBar1.add(menuPerfil);

        menuCadastrar.setText("Cadastrar");

        menuItemCadastrarLivro.setText("Livro");
        menuItemCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarLivroActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarLivro);

        menuItemCadastrarGenero.setText("Gênero");
        menuItemCadastrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarGeneroActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarGenero);

        menuItemCadastrarEditora.setText("Editora");
        menuItemCadastrarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarEditoraActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarEditora);

        menuItemCadastrarAutor.setText("Autor");
        menuItemCadastrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarAutorActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarAutor);

        jMenuBar1.add(menuCadastrar);

        menuVisualizar.setText("Visualizar");

        menuItemVisualizarLivros.setText("Livros");
        menuItemVisualizarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarLivrosActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarLivros);

        menuItemVisualizarGeneros.setText("Gêneros");
        menuItemVisualizarGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarGenerosActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarGeneros);

        menuItemVisualizarAutores.setText("Autores");
        menuItemVisualizarAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarAutoresActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarAutores);

        menuItemVisualizarEditoras.setText("Editoras");
        menuItemVisualizarEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarEditorasActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarEditoras);

        menuItemVisualizarSobrePrograma.setText("Sobre o programa");
        menuItemVisualizarSobrePrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarSobreProgramaActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarSobrePrograma);

        jMenuBar1.add(menuVisualizar);

        menuEmprestimo.setText("Empréstimo");

        menuItemEmprestimoEmprestar.setText("Emprestar");
        menuItemEmprestimoEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmprestimoEmprestarActionPerformed(evt);
            }
        });
        menuEmprestimo.add(menuItemEmprestimoEmprestar);

        menuItemEmprestimoVisualizar.setText("Visualizar");
        menuItemEmprestimoVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmprestimoVisualizarActionPerformed(evt);
            }
        });
        menuEmprestimo.add(menuItemEmprestimoVisualizar);

        jMenuBar1.add(menuEmprestimo);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });

        menuItemSairPrograma.setText("Sair programa");
        menuItemSairPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairProgramaActionPerformed(evt);
            }
        });
        menuSair.add(menuItemSairPrograma);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workStation)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workStation)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuItemSairProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairProgramaActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "O programa será fechado, deseja continuar?", "Continuar", JOptionPane.YES_NO_OPTION);
        if(resp == 0)
            System.exit(1);
    }//GEN-LAST:event_menuItemSairProgramaActionPerformed

    private void menuItemVisualizarGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarGenerosActionPerformed
        // TODO add your handling code here:
        openForm(new FormGenreTable());
    }//GEN-LAST:event_menuItemVisualizarGenerosActionPerformed

    private void menuItemVisualizarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarLivrosActionPerformed
        // TODO add your handling code here:
        openForm(new FormBookTable());
    }//GEN-LAST:event_menuItemVisualizarLivrosActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Deseja sair da conta?", "Continuar", JOptionPane.YES_NO_OPTION) == 0) 
        {
            FormLogin f = new FormLogin();
            this.setVisible(false);
            f.setVisible(true);
        }     
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuItemVisualizarSobreProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarSobreProgramaActionPerformed
        // TODO add your handling code here:
        openForm(new FormAboutProgram());
    }//GEN-LAST:event_menuItemVisualizarSobreProgramaActionPerformed

    private void menuItemCadastrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarGeneroActionPerformed
        // TODO add your handling code here:
        openForm(new FormRegisterGenre());
    }//GEN-LAST:event_menuItemCadastrarGeneroActionPerformed

    private void menuItemCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarLivroActionPerformed
        // TODO add your handling code here:
        openForm(new FormRegisterBook());
    }//GEN-LAST:event_menuItemCadastrarLivroActionPerformed

    private void menuItemCadastrarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarEditoraActionPerformed
        // TODO add your handling code here:
        openForm(new FormRegisterPublisher());
    }//GEN-LAST:event_menuItemCadastrarEditoraActionPerformed

    private void menuItemCadastrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarAutorActionPerformed
        // TODO add your handling code here:
        openForm(new FormRegisterAuthor());
    }//GEN-LAST:event_menuItemCadastrarAutorActionPerformed

    private void menuItemEmprestimoEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmprestimoEmprestarActionPerformed
        // TODO add your handling code here:
        openForm(new FormLoanBook());
    }//GEN-LAST:event_menuItemEmprestimoEmprestarActionPerformed

    private void menuItemEmprestimoVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmprestimoVisualizarActionPerformed
        // TODO add your handling code here:
        openForm(new FormLoanTable());
    }//GEN-LAST:event_menuItemEmprestimoVisualizarActionPerformed

    private void menuItemVisualizarAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarAutoresActionPerformed
        // TODO add your handling code here:
        openForm(new FormAuthorTable());
    }//GEN-LAST:event_menuItemVisualizarAutoresActionPerformed

    private void menuItemVisualizarEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarEditorasActionPerformed
        // TODO add your handling code here:
        openForm(new FormPublisherTable());
    }//GEN-LAST:event_menuItemVisualizarEditorasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuEmprestimo;
    private javax.swing.JMenuItem menuItemCadastrarAutor;
    private javax.swing.JMenuItem menuItemCadastrarEditora;
    private javax.swing.JMenuItem menuItemCadastrarGenero;
    private javax.swing.JMenuItem menuItemCadastrarLivro;
    private javax.swing.JMenuItem menuItemEmprestimoEmprestar;
    private javax.swing.JMenuItem menuItemEmprestimoVisualizar;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemSairPrograma;
    private javax.swing.JMenuItem menuItemVisualizarAutores;
    private javax.swing.JMenuItem menuItemVisualizarEditoras;
    private javax.swing.JMenuItem menuItemVisualizarGeneros;
    private javax.swing.JMenuItem menuItemVisualizarLivros;
    private javax.swing.JMenuItem menuItemVisualizarSobrePrograma;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuVisualizar;
    private javax.swing.JDesktopPane workStation;
    // End of variables declaration//GEN-END:variables
    
    public void openForm(JInternalFrame f){
       
        if (workStation.getAllFrames().length == 0){
            Dimension d = workStation.getSize();
            workStation.add(f);
            f.setLocation(
                (d.width- f.getWidth())/2,
                (d.height- f.getHeight())/2
            );
            f.setVisible(true);
        }
    }
}
